import dotenv from "dotenv";
dotenv.config({ quiet: true });

export const {
    JWT_SECRET,
    ENCRYPTION_KEY,
    MASTER_REGISTRATION_KEY,
    PORT,
    NODE_ENV,
    TURSO_DATABASE_URL,
    TURSO_AUTH_TOKEN,
    ACCESS_TOKEN_SECRET_KEY,
    REFRESH_TOKEN_SECRET_KEY,
    COOKIE_SECRET,
    CLOUD_NAME,
    CLOUD_API_KEY,
    CLOUD_API_SECRET,
    RUC_DNI_API_URL,
    BREVO_TOKEN,
    PUSHER_APP_ID,
    PUSHER_KEY,
    PUSHER_SECRET,
    PUSHER_CLUSTER,
    SRI_TAXPAYER_URL,
    SRI_ESTABLISHMENT_URL,
    SRI_CEDULA_URL,
    SRI_CAPTCHA_URL,
    SRI_VALIDAR_CAPTCHA_URL,
    SRI_ENVIRONMENT,
    SRI_RECEPCION_URL_PRUEBAS,
    SRI_RECEPCION_URL_PRODUCCION,
    SRI_AUTORIZACION_URL_PRUEBAS,
    SRI_AUTORIZACION_URL_PRODUCCION
} = process.env;